### PR TITLE
Adding phpMyAdmin on Dockerfile

### PR DESCRIPTION
**Pull request by guaychou**
Hey sir , i forked your repository and doing some modification on your Dockerfile code , to add phpMyAdmin version 4.8 , 

Thank you :)

### CODE REVIEW

**Comment by glats** [comment]
Hi @guaychou thnks for your contribution. I think that phpmyadmin is like a extra feature. With this I think i will put your changes in a branch and i will add it in the documentation.
What do you think?

Thnks again.

**Comment by guaychou** [comment]
It is up to you sir :) , 
I love to contribute :) , no problem :)
Thanks  sir

**Comment by glats** [comment]
nice!

**Comment by glats** [comment]
I did a pull request manually. So the new branch is **phpmyadmin-feature** f93a4959e2e1961ee2418c0633f5d3eaffb1f00c

**Pull request closed without merging**
